### ISSUE TITLE
Add optionnal banner while authenticating

### ISSUE THREAD

**Issue by maximumG** [ncouture/MockSSH#15]
The idea would be to get the possibility to specifiy a banner during SSH authentication.
The entry point would be to have an additional argument in the **runServer()** method to specify the banner.

This banner should cross all class until reaching **SSHTransport** class in the **connectionMade()** method where we can write the banner using **self.transport.wrtite(banner)**

**Comment by ncouture** [comment]
@maximumG Is there a chance you might be able to send a push request for this?

**Comment by ncouture** [comment]
~~I have nothing against adding this feature but would like it to be implemented by adding support for a configuration file.~~

**Comment by maximumG** [comment]
@ncouture : I will try to work on this and send you a push request. The first idea I had was not to have any configuration file but instead keep this project as a sort of API.

I have to say that I am working on a whole project on the top of MockSSH that will mimic many network device OS (IOS, NX-OS, F5,...) for some read-only commands ('show' commands) based on different configuration files.

**Comment by ncouture** [comment]
@maximumG It's great to hear people find the project useful.

Do you still need this feature or have you made your own implementation?

Since you are working on a whole project on top of MockSSH, I'd like to invite you to reach out to me to discuss your use-case in order to find out more about its applications and find out how to make it more useful.

email: nicolas.couture@gmail.com
